export enum TypeEquipe {
  TETE_A_TETE = 'TETE_A_TETE',
  DOUBLETTE = 'DOUBLETTE',
  TRIPLETTE = 'TRIPLETTE',
  QUADRETTE = 'QUADRETTE',
}

export const JOUEURS_PAR_TYPE: Record<TypeEquipe, number> = {
  [TypeEquipe.TETE_A_TETE]: 1,
  [TypeEquipe.DOUBLETTE]: 2,
  [TypeEquipe.TRIPLETTE]: 3,
  [TypeEquipe.QUADRETTE]: 4,
};

export enum TypePhase {
  POULES = 'POULES',
  ELIMINATION_SIMPLE = 'ELIMINATION_SIMPLE',
  ELIMINATION_DOUBLE = 'ELIMINATION_DOUBLE',
  SYSTEME_SUISSE = 'SYSTEME_SUISSE',
  CHAMPIONNAT = 'CHAMPIONNAT',
  CONSOLANTE = 'CONSOLANTE',
  BARRAGE = 'BARRAGE',
  REPECHAGE = 'REPECHAGE',
}

export enum StatutConcours {
  BROUILLON = 'BROUILLON',
  INSCRIPTIONS_OUVERTES = 'INSCRIPTIONS_OUVERTES',
  INSCRIPTIONS_CLOSES = 'INSCRIPTIONS_CLOSES',
  TIRAGE_EN_COURS = 'TIRAGE_EN_COURS',
  EN_COURS = 'EN_COURS',
  TERMINE = 'TERMINE',
  ARCHIVE = 'ARCHIVE',
}

export enum StatutMatch {
  PROGRAMME = 'PROGRAMME',
  EN_COURS = 'EN_COURS',
  SCORE_SAISI = 'SCORE_SAISI',
  TERMINE = 'TERMINE',
  FORFAIT = 'FORFAIT',
  ABANDON = 'ABANDON',
  BYE = 'BYE',
  EN_CORRECTION = 'EN_CORRECTION',
}

export enum StatutPhase {
  EN_ATTENTE = 'EN_ATTENTE',
  EN_COURS = 'EN_COURS',
  TERMINEE = 'TERMINEE',
}

export enum StatutTour {
  EN_ATTENTE = 'EN_ATTENTE',
  EN_COURS = 'EN_COURS',
  TERMINE = 'TERMINE',
}

export enum StatutInscription {
  CONFIRMEE = 'CONFIRMEE',
  ANNULEE = 'ANNULEE',
}

export enum CritereClassement {
  POINTS = 'POINTS',
  GOAL_AVERAGE_GENERAL = 'GOAL_AVERAGE_GENERAL',
  GOAL_AVERAGE_PARTICULIER = 'GOAL_AVERAGE_PARTICULIER',
  POINTS_MARQUES = 'POINTS_MARQUES',
  CONFRONTATION_DIRECTE = 'CONFRONTATION_DIRECTE',
  NOMBRE_VICTOIRES = 'NOMBRE_VICTOIRES',
  TIRAGE_AU_SORT = 'TIRAGE_AU_SORT',
}

export enum MethodeAppariement {
  ALEATOIRE = 'ALEATOIRE',
  SERPENTIN = 'SERPENTIN',
  SUISSE_STANDARD = 'SUISSE_STANDARD',
  SUISSE_BUCHHOLZ = 'SUISSE_BUCHHOLZ',
  DIRIGE = 'DIRIGE',
}

export enum TypeResultat {
  VICTOIRE = 'VICTOIRE',
  NUL = 'NUL',
  FORFAIT = 'FORFAIT',
  ABANDON = 'ABANDON',
  BYE = 'BYE',
}

export enum Role {
  ADMIN = 'ADMIN',
  ORGANISATEUR = 'ORGANISATEUR',
  ARBITRE = 'ARBITRE',
  SAISIE_SCORE = 'SAISIE_SCORE',
  CONSULTANT = 'CONSULTANT',
  JOUEUR_CONNECTE = 'JOUEUR_CONNECTE',
}

export enum TypeQualification {
  TOP_N = 'TOP_N',
  TOP_N_PER_POOL = 'TOP_N_PER_POOL',
  WINNER = 'WINNER',
  BEST_LOSERS = 'BEST_LOSERS',
}
